.TH tiler 1 "July 18, 2010" "tiler 0.1a"

.SH NAME
Tiler \(em Window tiling utility for X11

.SH SYNOPSIS
\fBtiler\fR [\fIoptions\fR]

.SH DESCRIPTION

.SH OPTIONS

.SH FILES

.TP
.I /usr/bin/tiler
Default binary location

.TP
.I ~/.config/tiler.conf
Default configuration file

.TP
.I /tmp/tiler.pid
PID file created to ensure single instance of the program


.SH ENVIRONMENT

The following environment variables are used:

.TP
.B DISPLAY
Specify the X display to be connected with.

.TP
.B HOME
User directory.

.SH SEE ALSO
.TP
.BR wmctrl (1)
.TP
.BR xdotool (1)
.TP
.B Home page
http://www.acadis.org/pages/tiler
.TP
.B Source code repository
http://www.github.com/gliss/tiler




.SH LICENSE
This program and its documentation are released under the terms of the
BSD license.

.SH AUTHOR
Manuel Vonthron (manuel.vonthron@acadis.org)
